language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: Miw5pe3+ws4Apy1wnLA+QC8XwaXRnx5S/Es4ocaGDuJpQB8MOS8LyGHXaT/CB8vrV/6yagjbcxisG9qSNIx13cPq7xsMz+HStfrJPv33PezM6a2QOSxwImOM4swl0nvctETz3vzYdCaxqoCj+ISMLGJn6Igl6vIRo5LoNnkAROaLgY2Y/45R1O6qdwLGivKDB/kjwTSghBHNAfSVYiE8KU3ZBFL5hDjv9To8hrDJturDgAQegvXcjCoUB1qJ5c5ZGDUeaO8ETK9vViDB16XaA3F+vO5cspN1zzXz8y3masTujpgUG0Ewf6CzMCr1Sc+NS+4OzWSzwQd8Jq/A5uIN5MmL5HWyr9wAFslaBAVEtmImQEW3GEFvRYTsCzhtMOXI97o3KasJtHMVRNgzbSpUuRwvg89chvuE3f4/0Bquc+WJamHIEn4anoDaoCDz5Hicz410rATB7q3LbpXP4bC46OHVMwFMprWYb+b8VVSDLDdICgwMtNgfsgCZ8rQA7ujBrRlosdDsT9a6fhOgv96ssLS/V/YtvqRekHeoDjgFoVDVz87KbzIU8CxtcQki/LbmU4rJ9Ebfm02+7zv07S+4P/dFM4/lGn8qtppV734zjNu45tJ4Bs6nOYbiyEsNFZfr52TzckZc1qSlCIiQCvxXe2st/nEmrKHra3QrFKaig8g=
  app: haxwheels
