language: node_js
before_script:
- yarn install
before_deploy:
- yarn run build
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: VCqy3eLx0ZUE29NXog23c4eK2zeNzT+FAjO9LQGzxX225cFh8gev4ShqUMCJzol7iXfA4bSUhVxdZRUFL2rQB5K2LcByNUYw14xmZLRQ0MuigsfCV8wQ5Lfn8Tc3C1P8NeFDsgAMwmW1Jh/BSus+j0jDvsQPhlQ+XTrb/KE0LC0xyQPrBaE+iGrHJ6LHCsyDJ6Rl60giFDOOuNPkFmTRjmXesljGOLeLAU190PiM2XbreOe/wkX6YS0YFdBH1aaRMUL+aTvqwAL44vDeVRwxV+6VVL/OgSC9pswv6K+L4sCbbacawvNc1y19G/FtzGO0PT5OpMydIiVBrm/PjI0G4D0u9YZKctRxDbHK7LFxDGpj6vNtPLzGh8l+BDax/w+3hwH5D+mUzFjYWtPwetNBE9TVbODOuRIQ1MkbfFQ+ROSKkE0079OwDMwLPLKECJVNsgf4FgL6G0ja9stKV1YFSIKy3m5sesjO+n1NLXzHMG1oETirvvBfTPdBRAVwHYsXBTtN04lZZhvppHJ7AxiPr51gUU8WnduznAuJwn7h2EPWyj9vu7sDql4J35n/pr3lGXrYxH4VhJHgjQ29FFg68vSZEYo8UVpADZ3CjPYWOpvqwDHT+wjsxQ5sFN5XL1R8MfobqKLyzYaOf5tPoo2b95AX9lGCIFUH/vxJOoVCvoM=
  app: haxwheels
  skip_cleanup: true
  on:
    repo: ScottyFillups/haxwheels
