language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  app: haxwheels
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: fcmLucbAVR6BfU3Dogl4RurTCs4ZIkzoMLelI5xFa5XE7sKhsJxTeBvCnykzeuWotLExDY17aP5p7arjERbr9XBd8i36Otw0736wrP45lh/l4/LCfh0Obc/fIXpHoYO110RX4QJyEuiJyzTqxx9Wcbi6uZsTuJRPdTYn/guGS12h/ttSHv+O7cukHTiFiUGCQ6pSj6QPO5kF32a2EpRQZaBbtnhKbg0ecTFmr4UGQAoGxB/uZr/P8ODTd5uvKupy/B5t3jVFYCF2Dna6jdKIvphiQ5AY2zFLNuOAKZI3Vnb9bMHowkw4Zbjt40Sx6TszCDluHbXgq+N3/DMua5j+km8jAV4kFN9LanfO1i4q+M51DVkzWv1OA1b5cOJZYGV1B1lOmQR0KgBfxX41AMeGlWAvJRsaDYrxKzaPrdUuOY8BR/s0CMAmb1mi4qMrtgqsT4sUfq3vjlm6TB+kKa9nSuhrMOtkd/5UekiPrUO9Tig0x0K205Ruv3A0BZbGoI8sqj+Lx/7RitLaBB6TJVdLaCGlbDhDO1zAwyMpw5qWvp8M5thtBVRJ6kb9RZCcfrdPwNKr7og1zGIIgr2YnYgHREoU7PMSHx9Bk16+tFd6qAimH7d163orhTr4fb55km39Jts4glhEkWtQhxd7PdbqO6ZfQMJchVt7dzeo1Bg+Lsw=
