language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: nnfQ9vY2o/IlRXlsvmw9RuQTrwBP1bKkB2xxun8hKg2gB7pLZF4fizMHAxtGD1oG1xeKzWdKEQKnc6K4YIod6nkWridEBDzmuhANe3loizfOnExyCFqGsw6V+aRTgFXTT9416QPgOVvlhbp7qG/2cNaWMyK7p2momFL18Z/72QF1oX/3t37vX8wkIEVY88PZhD5eOMFYNk7lU48/FUHdc2UPEVCKsyit6bU1rQRazuhQ2apQdzUElIq5guNgOl3MwllitnbPnbKnoOQFRVXc7lTjgHZsQ5RPXDIiLcuCG2RuaB2SnMx+9jouAR+ej2V133Hk3tzVN8LEZWdQekLsrw0Mb+edfUoZB3oD7xEoDNo/R1LokjSUEPoHB18ZFYSvFLd2HAAWmcDithTIYZ3NQZRqECgtXjcPABkkxipk+5IxSfNMEo5BXHtb5MPudF3yNdauJc1HYpUtyNWhWQ3cFVzx5v+cBVcyIN8dWaIWTg/DrCYpjl//FZRGbhlu4SYJBSyGMPXT9Gc3n5Upbej/RKWBxbrk6EhOJVNWQs0eLnQwVTV2lmWCTb/sZ6N9T9StIg4ZSrdeog1OTvsF4JEQAcMlLPzyIGwmHjAKyAFXd6YBLUfo3k8e8F1+HfokGfMj8LfVDEB4Sl0/zhLyJ5UhplFMm04sCzB1SEJvUSGQbIc=
  app: haxwheels
  on:
    repo: ScottyFillups/haxwheels
    branch: fixdeploy
