language: node_js
before_script:
- yarn install
- yarn run build
node_js:
- node
deploy:
  provider: heroku
  api_key:
    secure: NcYdlCEWClPdUbH6O0fBQ7Bx3Hlv4EHnCXU9d+tm7Btgh0P6hupIq72sxVqwKyowKCfyEzI2zHMcpYKScI0h1UrjnrBYHeQOoERvCLt+bkK7fHuEuFod3isPjGKJrfzVTyXha38yLfwv6zQxFR6v10jXAavzo1rycQO36n8YYhx8iISi+1085sXSCyberGW0dojmGvW/4ROatR+FTEMhWZuN8TfYJPVEJvJrZUlc+Jujt5iqmih/eNdoT7pgvN9/GS77JumH2+04VlhbeAXTzlLi1XWfihDR50VVviM/S+2TaPCzw7VCGc19z15T9nKDxfIQh4rhA7oht6AMG5mUC6Cuhx4pL2xG5a38Sb5Kj4iF5sM2nG3MvOmf/gHRw8ruxzii0CrvOsWe+PLU7FEzLQJU/Nx4XrPM4/VDEmHmjlj5YmIvJcncSoT8YI+PtpyteYEgLZyZCttMnubXht+/od3ujS6oIr402EMQBJ8YmdPl2zjUBUFVCR4//gCwDtTo3fhNZT/NszcFAPycTVtJ4oe/Djy5ioeirQB0mWb+faQQ4Jww5jWtvnEJxY8gaxCGXOLthLwHDmZaGNnx9rdEY4qHGQ6lkmBc/YxBQr2rysQnGKa3rnmawwmPAqgc/3JJ4SgbA9+ktfRmmmhkfdxvzdTb3sC02NaD+RZTK77rzHQ=
  app: haxwheels
  skip_cleanup: true
  on:
    repo: ScottyFillups/haxwheels
